demo – Foreng
demo Program
349 statements
Source File
Uses
chapter_4
chapter_5
chapter_6
chapter_7
Calls
Contents
Variables
i j ierr errmsg p7_6_real
Subroutines
chapter_select chapter_selected problem_select program_start program_end to_continue
Variables
Type Attributes Name Initial
integer :: i = 0
integer :: j = 0
integer :: ierr
character(len=100) :: errmsg
real :: p7_6_real = 1.0
Subroutines
subroutine chapter_select()
Arguments
None
subroutine chapter_selected(chp)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: chp
subroutine problem_select()
Arguments
None
subroutine program_start()
Arguments
None
subroutine program_end()
Arguments
None
subroutine to_continue()
Arguments
None
Call graph
demo calls p4_9, p7_5, p4_16, p4_3, p4_8, p6_6, p4_14, p7_4, p5_5, p4_17, p4_7, p5_6, p7_3, 50, p5_2, p6_10, p4_11, p4_5, problem_select, p5_3, p6_11, p7_1, chapter_selected, p4_18, p4_10, program_end, p5_4, p7_2, p4_6, chapter_select, p4_4, p7_7, p4_19, p7_6, p4_15, p4_1, p5_1, program_start, p4_12, p4_13
p4_17 calls is_alphnum, is_lower, is_upper, is_alph
p5_6 calls 10, 7, 80
problem_select calls 80
chapter_selected calls 80
p4_18 calls to_kelvin, 17, 250, calc_current_flow
program_end calls to_continue, 80
chapter_select calls 80
program_start calls 80
to_kelvin calls to_celcius
is_alphnum calls is_alph, is_num
is_alph calls is_lower, is_upper