misc_test – Foreng
misc_test Program
15 statements
Source File
Uses
foreng_math_misc
iso_fortran_env
Calls
Contents
None
Call graph
misc_test calls nth_root, factorial
nth_root calls nth_root_r32, nth_root_r64
factorial calls factorial_int16, factorial_int128, factorial_int32, factorial_int64
factorial_int16 calls factorial
factorial_int128 calls factorial
factorial_int32 calls factorial
factorial_int64 calls factorial