prob_test – Foreng
prob_test Program
25 statements
Source File
Uses
foreng_math
Calls
Contents
Variables
x x_2 test
Variables
Type Attributes Name Initial
integer, dimension(1000) :: x
real, dimension(100000) :: x_2
integer, dimension(8) :: test = [1, 2, 3, 4, 5, 6, 7, 8]
Call graph
prob_test calls std_dev, mean, fill_urand