trig_test – Foreng
trig_test Program
21 statements
Source File
Uses
foreng_math
Calls
Contents
Variables
thetad theta max_vals
Variables
Type Attributes Name Initial
real(kind=real64) :: thetad = 90
real(kind=real64) :: theta
real(kind=real64), dimension(3) :: max_vals = [-10.d0, 0d0, 5d0]
Call graph
trig_test calls atand, sinhd, tand, asind, sind, deg_to_rad, acosd