array_epsilon_r64 – Foreng
array_epsilon_r64 Function
6 statements
Source File
public function array_epsilon_r64(array) result(eps)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:) :: array
Return Value real(kind=real64)
Calls
Called by
Contents
None
Call graph
array_epsilon_r64 calls abs_max_val
abs_max_val calls abs_max_val_r64, abs_max_val_r32
array_epsilon calls array_epsilon_r64
intersection_r64 calls array_epsilon, belongs_to
belongs_to_r32 calls array_epsilon
belongs_to_r64 calls array_epsilon
intersection_r32 calls array_epsilon, belongs_to
belongs_to calls belongs_to_r32, belongs_to_r64
intersection calls intersection_r64, intersection_r32, intersection_int
union_r32 calls belongs_to
union_int calls belongs_to
intersection_int calls belongs_to
union_r64 calls belongs_to
union calls union_r32, union_int, union_r64