belongs_to_r32 – Foreng
belongs_to_r32 Function
23 statements
Source File
public function belongs_to_r32(x, A, eps) result(bool)
Check if a value belongs to a set within a certain tolerance . If is not specified, it will automatically calculated using the function
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: x
real(kind=real32), dimension(:) :: A
real(kind=real32), optional :: eps
Return Value logical
Calls
Called by
Contents
None
Call graph
belongs_to_r32 calls array_epsilon
array_epsilon calls array_epsilon_r32, array_epsilon_r64
array_epsilon_r32 calls abs_max_val
array_epsilon_r64 calls abs_max_val
abs_max_val calls abs_max_val_r64, abs_max_val_r32
belongs_to calls belongs_to_r32
union_int calls belongs_to
intersection_int calls belongs_to
union_r64 calls belongs_to
intersection_r32 calls belongs_to
union_r32 calls belongs_to
intersection_r64 calls belongs_to
union calls union_int, union_r64, union_r32
intersection calls intersection_int, intersection_r32, intersection_r64