belongs_to_int – Foreng
belongs_to_int Function
16 statements
Source File
public function belongs_to_int(x, A) result(bool)
Check if a value belongs to a set
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: x
integer, dimension(:) :: A
Return Value logical
Called by
Contents
None
Call graph
belongs_to calls belongs_to_int
union_int calls belongs_to
intersection_int calls belongs_to
union_r64 calls belongs_to
intersection_r32 calls belongs_to
union_r32 calls belongs_to
intersection_r64 calls belongs_to
union calls union_int, union_r64, union_r32
intersection calls intersection_int, intersection_r32, intersection_r64