exp_series_r32 – Foreng
exp_series_r32 Function
9 statements
Source File
public function exp_series_r32(x) result(exp)
Compute using a taylor series with 12 terms
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: x
Return Value real
Calls
Called by
Contents
None
Call graph
exp_series_r32 calls factorial
factorial calls factorial_int128, factorial_int16, factorial_int64, factorial_int32
factorial_int128 calls factorial
factorial_int16 calls factorial
factorial_int64 calls factorial
factorial_int32 calls factorial
exp_series calls exp_series_r32