factorial_int128 – Foreng
factorial_int128 Function
16 statements
Source File
public recursive function factorial_int128(x) result(x_fact)
Recursively compute the factorial of a 128-bit integer [supported on gfortran]. The max value that can be passed is 33 If x is less than 0 or greater 33, the function will return 0
Arguments
Type Intent Optional Attributes Name
integer(kind=int128), intent(in) :: x
Return Value integer(kind=int128)
Calls
Called by
Contents
None
Call graph
factorial_int128 calls factorial
factorial calls factorial_int128, factorial_int32, factorial_int16, factorial_int64
factorial_int32 calls factorial
factorial_int16 calls factorial
factorial_int64 calls factorial
misc_test calls factorial
exp_series_r32 calls factorial
sind_series calls factorial
exp_series_r64 calls factorial
poisson calls factorial
exp_series calls exp_series_r32, exp_series_r64