intersection_int – Foreng
intersection_int Function
25 statements
Source File
public function intersection_int(A, B) result(inters)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: A
set A
integer, intent(in), dimension(:) :: B
set B
Return Value integer, dimension(:),allocatable
Calls
Called by
Contents
None
Call graph
intersection_int calls belongs_to
belongs_to calls belongs_to_int, belongs_to_r32, belongs_to_r64
belongs_to_r32 calls array_epsilon
belongs_to_r64 calls array_epsilon
array_epsilon calls array_epsilon_r32, array_epsilon_r64
array_epsilon_r32 calls abs_max_val
array_epsilon_r64 calls abs_max_val
abs_max_val calls abs_max_val_r64, abs_max_val_r32
intersection calls intersection_int