intersection_r32 – Foreng
intersection_r32 Function
27 statements
Source File
public function intersection_r32(A, B) result(inters)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:) :: A
set A
real(kind=real32), intent(in), dimension(:) :: B
set B
Return Value real(kind=real32), dimension(:),allocatable
Calls
Called by
Contents
None
Call graph
intersection_r32 calls array_epsilon, belongs_to
array_epsilon calls array_epsilon_r64, array_epsilon_r32
belongs_to calls belongs_to_int, belongs_to_r32, belongs_to_r64
belongs_to_r32 calls array_epsilon
belongs_to_r64 calls array_epsilon
array_epsilon_r64 calls abs_max_val
array_epsilon_r32 calls abs_max_val
abs_max_val calls abs_max_val_r64, abs_max_val_r32
intersection calls intersection_r32