is_alph – Foreng
is_alph Function
8 statements
Source File
public function is_alph(char)
Test whether an ASCII character is a letter
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: char
Return Value logical
Calls
Called by
Contents
None
Call graph
is_alph calls is_upper, is_lower
is_alphnum calls is_alph
p4_17 calls is_alph, is_alphnum
demo calls p4_17