is_alph – Foreng
is_alph Function
8 statements
Source File
public elemental function is_alph(char)
Check if a character belongs to the alphabet This function checks the ASCII collating sequence of the passed character and returns true if the character belongs to the Roman alphabet.
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: char
Return Value logical
Calls
Called by
Contents
None
Call graph
is_alph calls is_upper, is_lower
is_alphnum calls is_alph