is_upper – Foreng
is_upper Function
10 statements
Source File
public function is_upper(char)
Test whether an ASCII character is an uppercase letter
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: char
Return Value logical
Called by
Contents
None
Call graph
p4_17 calls is_upper, is_alph, is_alphnum
to_lower calls is_upper
is_alph calls is_upper
demo calls p4_17
is_alphnum calls is_alph