lls_coefficient_fit – Foreng
lls_coefficient_fit Subroutine
11 statements
Source File
public subroutine lls_coefficient_fit(X, Y, m, b, r, stat)
Linear Least Squares Fit with correlation coefficient
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:) :: X
real(kind=real32), intent(in), dimension(:) :: Y
real(kind=real32), intent(out) :: m
real(kind=real32), intent(out) :: b
real(kind=real32), intent(out) :: r
integer, optional :: stat
Calls
Contents
None
Call graph
lls_coefficient_fit calls calc_correlation_coefficient_lls, lls_fit
lls_fit calls calc_m_lls, mean, calc_b_lls
calc_m_lls calls mean