p4_18 – Foreng
p4_18 Subroutine
27 statements
Source File
public subroutine p4_18()
Write a computer program to calculate the current flowing through this diode for all voltages from -1.0V to +0.6 V, in 0.1 V steps. Repeat this process for the following temperatures: 75F, 100F, and 125F
Arguments
None
Calls
Called by
Contents
None
Call graph
p4_18 calls 250, calc_current_flow, 17, to_kelvin
to_kelvin calls to_celcius
demo calls p4_18