point3_from_spherical_r64 – Foreng
point3_from_spherical_r64 Function
9 statements
Source File
public function point3_from_spherical_r64(rho, theta, phi) result(point)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: rho
real(kind=real64), intent(in) :: theta
real(kind=real64), intent(in) :: phi
Return Value type(point3)
Calls
Contents
None
Call graph
point3_from_spherical_r64 calls sind, cosd
sind calls sind_r64, sind_r32
cosd calls cosd_r64, cosd_r32
cosd_r64 calls deg_to_rad
sind_r64 calls deg_to_rad
sind_r32 calls deg_to_rad
cosd_r32 calls deg_to_rad
deg_to_rad calls deg_to_rad_r32, deg_to_rad_r64