poisson – Foreng
poisson Function
9 statements
Source File
public function poisson(k, t, lamda) result(P)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: k
real, intent(in) :: t
real, intent(in) :: lamda
Return Value real
Calls
Contents
None
Call graph
poisson calls factorial
factorial calls factorial_int64, factorial_int16, factorial_int32, factorial_int128
factorial_int64 calls factorial
factorial_int16 calls factorial
factorial_int32 calls factorial
factorial_int128 calls factorial