rad_to_deg_r32 – Foreng
rad_to_deg_r32 Function
4 statements
Source File
public elemental function rad_to_deg_r32(radians) result(degrees)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: radians
Return Value real(kind=real32)
Called by
Contents
None
Call graph
rad_to_deg calls rad_to_deg_r32
asind_r64 calls rad_to_deg
acosd_r32 calls rad_to_deg
acosd_r64 calls rad_to_deg
atand_r64 calls rad_to_deg
point3_phi calls rad_to_deg
atand_r32 calls rad_to_deg
point2_theta calls rad_to_deg
asind_r32 calls rad_to_deg
point3_theta calls rad_to_deg
acosd calls acosd_r32, acosd_r64
asind calls asind_r64, asind_r32
atand calls atand_r64, atand_r32