rank1_root_mean_squared_mean_i32 – Foreng
rank1_root_mean_squared_mean_i32 Function
7 statements
Source File
public function rank1_root_mean_squared_mean_i32(data_) result(rms_)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: data_(:)
Return Value real(kind=real32)
Rank 1 array containing the elements to calculate the mean for
Called by
Contents
None
Call graph
rms_mean calls rank1_root_mean_squared_mean_i32
rank_1_mean_i64 calls rms_mean
rank_1_mean_r64 calls rms_mean
rank_1_mean_r32 calls rms_mean
rank_1_mean_i32 calls rms_mean
mean calls rank_1_mean_i64, rank_1_mean_r64, rank_1_mean_r32, rank_1_mean_i32
std_dev_r64 calls mean
std_dev_r32 calls mean
std_dev_i32 calls mean
std_dev_i64 calls mean
std_dev calls std_dev_r64, std_dev_r32, std_dev_i32, std_dev_i64