rank_1_mean_i32 – Foreng
rank_1_mean_i32 Function
21 statements
Source File
public function rank_1_mean_i32(data_, type) result(mean_)
Calculate the mean of a 1d data set, given the "type"
Check which mean to call
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in), dimension(:) :: data_
character(len=*), intent(in), optional :: type
Return Value real(kind=real32)
Calls
Called by
Contents
None
Call graph
rank_1_mean_i32 calls rms_mean, harmonic_mean, arithmetic_mean, geometric_mean
rms_mean calls rank1_root_mean_squared_mean_i64, rank1_root_mean_squared_mean_r32, rank1_root_mean_squared_mean_r64, rank1_root_mean_squared_mean_i32
harmonic_mean calls rank1_harmonic_mean_i32, rank1_harmonic_mean_r32, rank1_harmonic_mean_i64, rank1_harmonic_mean_r64
arithmetic_mean calls rank1_arithmetic_mean_r32, rank1_arithmetic_mean_i32, rank1_arithmetic_mean_i64, rank1_arithmetic_mean_r64
geometric_mean calls rank1_geometric_mean_i64, rank1_geometric_mean_r64, rank1_geometric_mean_r32, rank1_geometric_mean_i32
rank1_geometric_mean_i64 calls nth_root
rank1_geometric_mean_r64 calls nth_root
rank1_geometric_mean_r32 calls nth_root
nth_root calls nth_root_r64, nth_root_r32
mean calls rank_1_mean_i32
std_dev_r64 calls mean
std_dev_i64 calls mean
std_dev_r32 calls mean
std_dev_i32 calls mean
std_dev calls std_dev_r64, std_dev_i64, std_dev_r32, std_dev_i32