rank1_geometric_mean_i64 – Foreng
rank1_geometric_mean_i64 Function
7 statements
Source File
public function rank1_geometric_mean_i64(data_) result(geometric_mean_)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: data_(:)
Return Value real(kind=real64)
Rank 1 array containing the elements to calculate the mean for
Calls
Called by
Contents
None
Call graph
rank1_geometric_mean_i64 calls nth_root
nth_root calls nth_root_r32, nth_root_r64
geometric_mean calls rank1_geometric_mean_i64
rank_1_mean_i64 calls geometric_mean
rank_1_mean_r64 calls geometric_mean
rank_1_mean_r32 calls geometric_mean
rank_1_mean_i32 calls geometric_mean
mean calls rank_1_mean_i64, rank_1_mean_r64, rank_1_mean_r32, rank_1_mean_i32
std_dev_r64 calls mean
std_dev_r32 calls mean
std_dev_i32 calls mean
std_dev_i64 calls mean
std_dev calls std_dev_r64, std_dev_r32, std_dev_i32, std_dev_i64