sind_series – Foreng
sind_series Function
11 statements
Source File
public function sind_series(x_, n_) result(sin_x)
Compute sine using a truncated taylor series
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x_
Angle in degrees
integer, intent(in) :: n_
Number of terms to use
Return Value real
Calls
Contents
None
Call graph
sind_series calls factorial, deg_to_rad
factorial calls factorial_int64, factorial_int16, factorial_int32, factorial_int128
deg_to_rad calls deg_to_rad_r32, deg_to_rad_r64
factorial_int64 calls factorial
factorial_int16 calls factorial
factorial_int32 calls factorial
factorial_int128 calls factorial