sind_r64 – Foreng
sind_r64 Function
4 statements
Source File
public elemental function sind_r64(theta) result(sind)
Double precision
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: theta
in degrees
Return Value real(kind=real64)
Calls
Called by
Contents
None
Call graph
sind_r64 calls deg_to_rad
deg_to_rad calls deg_to_rad_r32, deg_to_rad_r64
sind calls sind_r64
point2_from_polar_int calls sind
point3_from_spherical_int calls sind
point3_from_spherical_r32 calls sind
point2_from_polar_r32 calls sind
point3_from_spherical_r64 calls sind
point2_from_polar_r64 calls sind