std_dev_i32 – Foreng
std_dev_i32 Function
9 statements
Source File
public function std_dev_i32(data_) result(sigma)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in), dimension(:) :: data_
Return Value real(kind=real32)
population standard deviation
Calls
Called by
Contents
None
Call graph
std_dev_i32 calls mean
mean calls rank_1_mean_i64, rank_1_mean_r64, rank_1_mean_r32, rank_1_mean_i32
rank_1_mean_i64 calls geometric_mean, rms_mean, arithmetic_mean, harmonic_mean
rank_1_mean_r64 calls geometric_mean, rms_mean, arithmetic_mean, harmonic_mean
rank_1_mean_r32 calls geometric_mean, rms_mean, arithmetic_mean, harmonic_mean
rank_1_mean_i32 calls geometric_mean, rms_mean, arithmetic_mean, harmonic_mean
geometric_mean calls rank1_geometric_mean_i64, rank1_geometric_mean_r32, rank1_geometric_mean_r64, rank1_geometric_mean_i32
rms_mean calls rank1_root_mean_squared_mean_r64, rank1_root_mean_squared_mean_r32, rank1_root_mean_squared_mean_i32, rank1_root_mean_squared_mean_i64
arithmetic_mean calls rank1_arithmetic_mean_i32, rank1_arithmetic_mean_r64, rank1_arithmetic_mean_r32, rank1_arithmetic_mean_i64
harmonic_mean calls rank1_harmonic_mean_i64, rank1_harmonic_mean_i32, rank1_harmonic_mean_r32, rank1_harmonic_mean_r64
rank1_geometric_mean_i64 calls nth_root
rank1_geometric_mean_r32 calls nth_root
rank1_geometric_mean_r64 calls nth_root
nth_root calls nth_root_r32, nth_root_r64
std_dev calls std_dev_i32