union_r64 – Foreng
union_r64 Function
16 statements
Source File
public function union_r64(A, B) result(union_set)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:) :: A
set A
real(kind=real64), intent(in), dimension(:) :: B
set B
Return Value real(kind=real64), dimension(:),allocatable
Calls
Called by
Contents
None
Call graph
union_r64 calls belongs_to
belongs_to calls belongs_to_int, belongs_to_r64, belongs_to_r32
belongs_to_r64 calls array_epsilon
belongs_to_r32 calls array_epsilon
array_epsilon calls array_epsilon_r64, array_epsilon_r32
array_epsilon_r64 calls abs_max_val
array_epsilon_r32 calls abs_max_val
abs_max_val calls abs_max_val_r64, abs_max_val_r32
union calls union_r64