urand_r64 – Foreng
urand_r64 Function
13 statements
Source File
public function urand_r64(min, max) result(x)
Return a uniform random variable [min, max)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: min
, inclusive
real(kind=real64), intent(in) :: max
, exclusive
Return Value real(kind=real64)
Called by
Contents
None
Call graph
urand calls urand_r64
standard_normal_rand calls urand_r64
fill_urand_rank2_r32 calls urand
fill_urand_rank1_r64 calls urand
fill_urand_rank3_i32 calls urand
fill_urand_rank3_r32 calls urand
fill_urand_rank1_r32 calls urand
fill_urand_rank2_r64 calls urand
fill_urand_rank3_i64 calls urand
fill_urand_rank2_i64 calls urand
fill_urand_rank1_i64 calls urand
fill_urand_rank3_r64 calls urand
fill_urand_rank2_i32 calls urand
fill_urand_rank1_i32 calls urand
fill_urand calls fill_urand_rank2_r32, fill_urand_rank1_r64, fill_urand_rank3_i32, fill_urand_rank3_r32, fill_urand_rank1_r32, fill_urand_rank2_r64, fill_urand_rank3_i64, fill_urand_rank2_i64, fill_urand_rank1_i64, fill_urand_rank3_r64, fill_urand_rank2_i32, fill_urand_rank1_i32