abs_max_val – Foreng
abs_max_val Interface
4 statements
Source File
public interface abs_max_val
Calls
Called by
Contents
Module Procedures
abs_max_val_r32 abs_max_val_r64
Module Procedures
public function abs_max_val_r32(array) result(abs_max_val)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:) :: array
Return Value real(kind=real32)
public function abs_max_val_r64(array) result(abs_max_val)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:) :: array
Return Value real(kind=real64)
Call graph
abs_max_val calls abs_max_val_r64, abs_max_val_r32
array_epsilon_r64 calls abs_max_val
array_epsilon_r32 calls abs_max_val
array_epsilon calls array_epsilon_r64, array_epsilon_r32
intersection_r32 calls array_epsilon, belongs_to
belongs_to_r32 calls array_epsilon
belongs_to_r64 calls array_epsilon
intersection_r64 calls array_epsilon, belongs_to
intersection calls intersection_r32, intersection_r64, intersection_int
belongs_to calls belongs_to_r32, belongs_to_r64
intersection_int calls belongs_to
union_int calls belongs_to
union_r64 calls belongs_to
union_r32 calls belongs_to
union calls union_int, union_r64, union_r32