acosd – Foreng
acosd Interface
4 statements
Source File
public interface acosd
Calculate and return in degrees
real(real32) :: x_r32 = 1
real(real64) :: x_r64 = 0
print *, acosd(x_r32) ! = 0.000
print *, acosd(x_r64) ! = 90.000
Calls
Contents
Module Procedures
acosd_r32 acosd_r64
Module Procedures
public elemental function acosd_r32(x) result(theta)
Single precision
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: x
Return Value real(kind=real32)
in degrees
public elemental function acosd_r64(x) result(theta)
Double precision
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: x
Return Value real(kind=real64)
in degrees
Call graph
acosd calls acosd_r32, acosd_r64
acosd_r32 calls rad_to_deg
acosd_r64 calls rad_to_deg
rad_to_deg calls rad_to_deg_r32, rad_to_deg_r64