belongs_to – Foreng
belongs_to Interface
5 statements
Source File
public interface belongs_to
Check if
belongs to if there is at least one element in for which
Calls
Called by
Contents
Module Procedures
belongs_to_int belongs_to_r32 belongs_to_r64
Module Procedures
public function belongs_to_int(x, A) result(bool)
Check if a value belongs to a set
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: x
integer, dimension(:) :: A
Return Value logical
public function belongs_to_r32(x, A, eps) result(bool)
Check if a value belongs to a set within a certain tolerance . If is not specified, it will automatically calculated using the function
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: x
real(kind=real32), dimension(:) :: A
real(kind=real32), optional :: eps
Return Value logical
public function belongs_to_r64(x, A, eps) result(bool)
Check if a value belongs to a set within a certain tolerance . If is not specified, it will automatically calculated using the function
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: x
real(kind=real64), dimension(:) :: A
real(kind=real64), optional :: eps
Return Value logical
Call graph
belongs_to calls belongs_to_int, belongs_to_r64, belongs_to_r32
belongs_to_r64 calls array_epsilon
belongs_to_r32 calls array_epsilon
array_epsilon calls array_epsilon_r64, array_epsilon_r32
array_epsilon_r64 calls abs_max_val
array_epsilon_r32 calls abs_max_val
abs_max_val calls abs_max_val_r64, abs_max_val_r32
intersection_int calls belongs_to
intersection_r64 calls belongs_to
union_r32 calls belongs_to
intersection_r32 calls belongs_to
union_int calls belongs_to
union_r64 calls belongs_to
intersection calls intersection_int, intersection_r64, intersection_r32
union calls union_r32, union_int, union_r64