celcius_to_fahrenheit – Foreng
celcius_to_fahrenheit Interface
4 statements
Source File
public interface celcius_to_fahrenheit
Calls
Called by
Contents
Module Procedures
celcius_to_fahrenheit_r32 celcius_to_fahrenheit_r64
Module Procedures
public elemental function celcius_to_fahrenheit_r32(C) result(F)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: C
Return Value real(kind=real32)
public elemental function celcius_to_fahrenheit_r64(C) result(F)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: C
Return Value real(kind=real64)
Call graph
celcius_to_fahrenheit calls celcius_to_fahrenheit_r64, celcius_to_fahrenheit_r32
kelvin_to_fahrenheit_r64 calls celcius_to_fahrenheit
kelvin_to_fahrenheit_r32 calls celcius_to_fahrenheit
fahrenheit_to_kelvin_r64 calls celcius_to_fahrenheit
fahrenheit_to_kelvin calls fahrenheit_to_kelvin_r64
kelvin_to_fahrenheit calls kelvin_to_fahrenheit_r64, kelvin_to_fahrenheit_r32