cosd – Foreng
cosd Interface
4 statements
Source File
public interface cosd
Calculate where is in degrees
real(real32) :: theta_r32 = 90
real(real64) :: theta_r64 = 60
print *, cosd(theta_r32) ! = 0.000
print *, cosd(theta_r64) ! = 0.500
Calls
Called by
Contents
Module Procedures
cosd_r32 cosd_r64
Module Procedures
public elemental function cosd_r32(theta) result(cosd)
Single precision
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: theta
in degrees
Return Value real(kind=real32)
public elemental function cosd_r64(theta) result(cosd)
Double precision
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: theta
in degrees
Return Value real(kind=real64)
Call graph
cosd calls cosd_r32, cosd_r64
cosd_r32 calls deg_to_rad
cosd_r64 calls deg_to_rad
deg_to_rad calls deg_to_rad_r32, deg_to_rad_r64
point3_from_spherical_r64 calls cosd
point2_from_polar_int calls cosd
point2_from_polar_r64 calls cosd
point3_from_spherical_int calls cosd
point3_from_spherical_r32 calls cosd
point2_from_polar_r32 calls cosd