deg_to_rad – Foreng
deg_to_rad Interface
4 statements
Source File
public interface deg_to_rad
Convert from degrees to radians
Calls
Called by
Contents
Module Procedures
deg_to_rad_r32 deg_to_rad_r64
Module Procedures
public elemental function deg_to_rad_r32(degrees) result(radians)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: degrees
Return Value real(kind=real32)
public elemental function deg_to_rad_r64(degrees) result(radians)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: degrees
Return Value real(kind=real64)
Call graph
deg_to_rad calls deg_to_rad_r32, deg_to_rad_r64
sind_r64 calls deg_to_rad
sinhd_r32 calls deg_to_rad
coshd_r32 calls deg_to_rad
tanhd_r64 calls deg_to_rad
coshd_r64 calls deg_to_rad
sind_series calls deg_to_rad
tanhd_r32 calls deg_to_rad
tand_r64 calls deg_to_rad
tand_r32 calls deg_to_rad
sind_r32 calls deg_to_rad
cosd_r32 calls deg_to_rad
vector3_angle_between_vector3 calls deg_to_rad
cosd_r64 calls deg_to_rad
sinhd_r64 calls deg_to_rad
coshd calls coshd_r32, coshd_r64
sind calls sind_r64, sind_r32
sinhd calls sinhd_r32, sinhd_r64
tand calls tand_r64, tand_r32
tanhd calls tanhd_r64, tanhd_r32
cosd calls cosd_r32, cosd_r64
point3_from_spherical_r64 calls sind, cosd
point2_from_polar_int calls sind, cosd
point2_from_polar_r64 calls sind, cosd
point3_from_spherical_int calls sind, cosd
point3_from_spherical_r32 calls sind, cosd
point2_from_polar_r32 calls sind, cosd