exp_series – Foreng
exp_series Interface
4 statements
Source File
public interface exp_series
Compute using a truncated taylor series
Calls
Contents
Module Procedures
exp_series_r32 exp_series_r64
Module Procedures
public function exp_series_r32(x) result(exp)
Compute using a taylor series with 12 terms
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: x
Return Value real
public function exp_series_r64(x) result(exp)
Calculate using a taylor series with 20 terms
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: x
Return Value real(kind=real64)
Call graph
exp_series calls exp_series_r64, exp_series_r32
exp_series_r64 calls factorial
exp_series_r32 calls factorial
factorial calls factorial_int64, factorial_int16, factorial_int32, factorial_int128
factorial_int64 calls factorial
factorial_int16 calls factorial
factorial_int32 calls factorial
factorial_int128 calls factorial