factorial – Foreng
factorial Interface
6 statements
Source File
public interface factorial
Compute
Calls
Called by
Contents
Module Procedures
factorial_int16 factorial_int32 factorial_int64 factorial_int128
Module Procedures
public recursive function factorial_int16(x) result(x_fact)
Recursively compute the factorial of a 16-bit integer. The max value that can be passed is 7 If x is less than 0 or greater 7, the function will return 0
Arguments
Type Intent Optional Attributes Name
integer(kind=int16), intent(in) :: x
Return Value integer(kind=int16)
public recursive function factorial_int32(x) result(x_fact)
Recursively compute the factorial of a 32-bit integer. The max value that can be passed is 16 If x is less than 0 or greater 16, the function will return 0
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x
Return Value integer(kind=int32)
public recursive function factorial_int64(x) result(x_fact)
Recursively compute the factorial of a 64-bit integer. The max value that can be passed is 20 If x is less than 0 or greater 20, the function will return 0
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x
Return Value integer(kind=int64)
public recursive function factorial_int128(x) result(x_fact)
Recursively compute the factorial of a 128-bit integer [supported on gfortran]. The max value that can be passed is 33 If x is less than 0 or greater 33, the function will return 0
Arguments
Type Intent Optional Attributes Name
integer(kind=int128), intent(in) :: x
Return Value integer(kind=int128)
Call graph
factorial calls factorial_int64, factorial_int16, factorial_int32, factorial_int128
factorial_int64 calls factorial
factorial_int16 calls factorial
factorial_int32 calls factorial
factorial_int128 calls factorial
poisson calls factorial
misc_test calls factorial
sind_series calls factorial
exp_series_r64 calls factorial
exp_series_r32 calls factorial
exp_series calls exp_series_r64, exp_series_r32