fahrenheit_to_kelvin – Foreng
fahrenheit_to_kelvin Interface
4 statements
Source File
public interface fahrenheit_to_kelvin
Calls
Contents
Module Procedures
fahrenheit_to_kelvin_r32 fahrenheit_to_kelvin_r64
Module Procedures
public elemental function fahrenheit_to_kelvin_r32(F) result(K)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: F
Return Value real(kind=real32)
public elemental function fahrenheit_to_kelvin_r64(F) result(K)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: F
Return Value real(kind=real64)
Call graph
fahrenheit_to_kelvin calls fahrenheit_to_kelvin_r32, fahrenheit_to_kelvin_r64
fahrenheit_to_kelvin_r32 calls fahrenheit_to_celcius, celcius_to_kelvin
fahrenheit_to_kelvin_r64 calls celcius_to_fahrenheit, kelvin_to_celcius
celcius_to_fahrenheit calls celcius_to_fahrenheit_r32, celcius_to_fahrenheit_r64
kelvin_to_celcius calls kelvin_to_celcius_r64, kelvin_to_celcius_r32
fahrenheit_to_celcius calls fahrenheit_to_celcius_r32, fahrenheit_to_celcius_r64
celcius_to_kelvin calls celcius_to_kelvin_r32, celcius_to_kelvin_r64