geometric_mean – Foreng
geometric_mean Interface
6 statements
Source File
public interface geometric_mean
Calls
Called by
Contents
Module Procedures
rank1_geometric_mean_r32 rank1_geometric_mean_r64 rank1_geometric_mean_i32 rank1_geometric_mean_i64
Module Procedures
public function rank1_geometric_mean_r32(data_) result(geometric_mean_)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: data_(:)
Return Value real(kind=real32)
Rank 1 array containing the elements to calculate the mean for
public function rank1_geometric_mean_r64(data_) result(geometric_mean_)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: data_(:)
Return Value real(kind=real64)
Rank 1 array containing the elements to calculate the mean for
public function rank1_geometric_mean_i32(data_) result(geometric_mean_)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: data_(:)
Return Value real(kind=real64)
Rank 1 array containing the elements to calculate the mean for
public function rank1_geometric_mean_i64(data_) result(geometric_mean_)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: data_(:)
Return Value real(kind=real64)
Rank 1 array containing the elements to calculate the mean for
Call graph
geometric_mean calls rank1_geometric_mean_r64, rank1_geometric_mean_i64, rank1_geometric_mean_r32, rank1_geometric_mean_i32
rank1_geometric_mean_r64 calls nth_root
rank1_geometric_mean_i64 calls nth_root
rank1_geometric_mean_r32 calls nth_root
nth_root calls nth_root_r32, nth_root_r64
rank_1_mean_i64 calls geometric_mean
rank_1_mean_r64 calls geometric_mean
rank_1_mean_r32 calls geometric_mean
rank_1_mean_i32 calls geometric_mean
mean calls rank_1_mean_i64, rank_1_mean_r64, rank_1_mean_r32, rank_1_mean_i32
std_dev_r64 calls mean
std_dev_r32 calls mean
std_dev_i32 calls mean
std_dev_i64 calls mean
std_dev calls std_dev_r64, std_dev_r32, std_dev_i32, std_dev_i64