intersection – Foreng
intersection Interface
5 statements
Source File
public interface intersection
Compute the intersection of two sets
Calls
Contents
Module Procedures
intersection_int intersection_r32 intersection_r64
Module Procedures
public function intersection_int(A, B) result(inters)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: A
set A
integer, intent(in), dimension(:) :: B
set B
Return Value integer, dimension(:), allocatable
public function intersection_r32(A, B) result(inters)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:) :: A
set A
real(kind=real32), intent(in), dimension(:) :: B
set B
Return Value real(kind=real32), dimension(:), allocatable
public function intersection_r64(A, B) result(inters)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:) :: A
set A
real(kind=real64), intent(in), dimension(:) :: B
set B
Return Value real(kind=real64), dimension(:), allocatable
Call graph
intersection calls intersection_r64, intersection_int, intersection_r32
intersection_r64 calls belongs_to, array_epsilon
intersection_int calls belongs_to
intersection_r32 calls belongs_to, array_epsilon
belongs_to calls belongs_to_r64, belongs_to_int, belongs_to_r32
array_epsilon calls array_epsilon_r32, array_epsilon_r64
array_epsilon_r32 calls abs_max_val
belongs_to_r64 calls array_epsilon
belongs_to_r32 calls array_epsilon
array_epsilon_r64 calls abs_max_val
abs_max_val calls abs_max_val_r64, abs_max_val_r32