mean – Foreng
mean Interface
6 statements
Source File
public interface mean
Calls
Called by
Contents
Module Procedures
rank_1_mean_r32 rank_1_mean_r64 rank_1_mean_i32 rank_1_mean_i64
Module Procedures
public function rank_1_mean_r32(data_, type) result(mean_)
Calculate the mean of a 1d data set, given the "type"
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:) :: data_
character(len=*), intent(in), optional :: type
Return Value real(kind=real32)
public function rank_1_mean_r64(data_, type) result(mean_)
Calculate the mean of a 1d data set, given the "type"
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:) :: data_
character(len=*), intent(in), optional :: type
Return Value real(kind=real64)
public function rank_1_mean_i32(data_, type) result(mean_)
Calculate the mean of a 1d data set, given the "type"
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in), dimension(:) :: data_
character(len=*), intent(in), optional :: type
Return Value real(kind=real32)
public function rank_1_mean_i64(data_, type) result(mean_)
Calculate the mean of a 1d data set, given the "type"
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in), dimension(:) :: data_
character(len=*), intent(in), optional :: type
Return Value real(kind=real64)
Call graph
mean calls rank_1_mean_i64, rank_1_mean_r64, rank_1_mean_r32, rank_1_mean_i32
rank_1_mean_i64 calls geometric_mean, rms_mean, arithmetic_mean, harmonic_mean
rank_1_mean_r64 calls geometric_mean, rms_mean, arithmetic_mean, harmonic_mean
rank_1_mean_r32 calls geometric_mean, rms_mean, arithmetic_mean, harmonic_mean
rank_1_mean_i32 calls geometric_mean, rms_mean, arithmetic_mean, harmonic_mean
geometric_mean calls rank1_geometric_mean_i64, rank1_geometric_mean_r32, rank1_geometric_mean_r64, rank1_geometric_mean_i32
rms_mean calls rank1_root_mean_squared_mean_r64, rank1_root_mean_squared_mean_r32, rank1_root_mean_squared_mean_i32, rank1_root_mean_squared_mean_i64
arithmetic_mean calls rank1_arithmetic_mean_i32, rank1_arithmetic_mean_r64, rank1_arithmetic_mean_r32, rank1_arithmetic_mean_i64
harmonic_mean calls rank1_harmonic_mean_i64, rank1_harmonic_mean_i32, rank1_harmonic_mean_r32, rank1_harmonic_mean_r64
rank1_geometric_mean_i64 calls nth_root
rank1_geometric_mean_r32 calls nth_root
rank1_geometric_mean_r64 calls nth_root
nth_root calls nth_root_r32, nth_root_r64
std_dev_r64 calls mean
std_dev_r32 calls mean
std_dev_i32 calls mean
std_dev_i64 calls mean
std_dev calls std_dev_r64, std_dev_r32, std_dev_i32, std_dev_i64