nth_root – Foreng
nth_root Interface
4 statements
Source File
public interface nth_root
Compute
Calls
Called by
Contents
Module Procedures
nth_root_r32 nth_root_r64
Module Procedures
public function nth_root_r32(x_, n_) result(root_)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: x_
integer, intent(in) :: n_
Return Value real(kind=real32)
public function nth_root_r64(x_, n_) result(root_)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: x_
integer, intent(in) :: n_
Return Value real(kind=real64)
Call graph
nth_root calls nth_root_r64, nth_root_r32
rank1_geometric_mean_r64 calls nth_root
rank1_geometric_mean_r32 calls nth_root
rank1_geometric_mean_i64 calls nth_root
misc_test calls nth_root
geometric_mean calls rank1_geometric_mean_r64, rank1_geometric_mean_r32, rank1_geometric_mean_i64
rank_1_mean_r64 calls geometric_mean
rank_1_mean_i32 calls geometric_mean
rank_1_mean_r32 calls geometric_mean
rank_1_mean_i64 calls geometric_mean
mean calls rank_1_mean_r64, rank_1_mean_i32, rank_1_mean_r32, rank_1_mean_i64
std_dev_r64 calls mean
std_dev_i64 calls mean
std_dev_r32 calls mean
std_dev_i32 calls mean
std_dev calls std_dev_r64, std_dev_i64, std_dev_r32, std_dev_i32