operator(*) – Foreng
operator(*) Interface
5 statements
Source File
public interface operator(*)
Calls
Contents
Module Procedures
scalar_times_vector3_r32 scalar_times_vector3_r64 scalar_times_vector3_int
Module Procedures
public function scalar_times_vector3_r32(k, v1) result(v2)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: k
class(vector3), intent(in) :: v1
Return Value type(vector3)
public function scalar_times_vector3_r64(k, v1) result(v2)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: k
class(vector3), intent(in) :: v1
Return Value type(vector3)
public function scalar_times_vector3_int(k, v1) result(v2)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: k
class(vector3), intent(in) :: v1
Return Value type(vector3)
Call graph
operator(*) calls scalar_times_vector3_r32, scalar_times_vector3_int, scalar_times_vector3_r64