sind – Foreng
sind Interface
4 statements
Source File
public interface sind
Calculate where is in degrees
real(real32) :: theta_r32 = 90
real(real64) :: theta_r64 = 30
print *, sind(theta_r32) ! = 1.000
print *, sind(theta_r64) ! = 0.500
Calls
Called by
Contents
Module Procedures
sind_r32 sind_r64
Module Procedures
public elemental function sind_r32(theta) result(sind)
Single precision
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: theta
in degrees
Return Value real(kind=real32)
public elemental function sind_r64(theta) result(sind)
Double precision
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: theta
in degrees
Return Value real(kind=real64)
Call graph
sind calls sind_r64, sind_r32
sind_r64 calls deg_to_rad
sind_r32 calls deg_to_rad
deg_to_rad calls deg_to_rad_r32, deg_to_rad_r64
point3_from_spherical_r64 calls sind
point2_from_polar_int calls sind
point2_from_polar_r64 calls sind
point3_from_spherical_int calls sind
point3_from_spherical_r32 calls sind
point2_from_polar_r32 calls sind