std_dev – Foreng
std_dev Interface
6 statements
Source File
public interface std_dev
Calls
Contents
Module Procedures
std_dev_r32 std_dev_r64 std_dev_i32 std_dev_i64
Module Procedures
public function std_dev_r32(data) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:) :: data
Return Value real(kind=real32)
population standard deviation
public function std_dev_r64(data) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:) :: data
Return Value real(kind=real64)
population standard deviation
public function std_dev_i32(data_) result(sigma)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in), dimension(:) :: data_
Return Value real(kind=real32)
population standard deviation
public function std_dev_i64(data) result(sigma)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in), dimension(:) :: data
Return Value real(kind=real64)
population standard deviation
Call graph
std_dev calls std_dev_r64, std_dev_i64, std_dev_r32, std_dev_i32
std_dev_r64 calls mean
std_dev_i64 calls mean
std_dev_r32 calls mean
std_dev_i32 calls mean
mean calls rank_1_mean_r64, rank_1_mean_i32, rank_1_mean_r32, rank_1_mean_i64
rank_1_mean_r64 calls rms_mean, harmonic_mean, arithmetic_mean, geometric_mean
rank_1_mean_i32 calls rms_mean, harmonic_mean, arithmetic_mean, geometric_mean
rank_1_mean_r32 calls rms_mean, harmonic_mean, arithmetic_mean, geometric_mean
rank_1_mean_i64 calls rms_mean, harmonic_mean, arithmetic_mean, geometric_mean
rms_mean calls rank1_root_mean_squared_mean_i64, rank1_root_mean_squared_mean_r32, rank1_root_mean_squared_mean_r64, rank1_root_mean_squared_mean_i32
harmonic_mean calls rank1_harmonic_mean_i32, rank1_harmonic_mean_r32, rank1_harmonic_mean_i64, rank1_harmonic_mean_r64
arithmetic_mean calls rank1_arithmetic_mean_r32, rank1_arithmetic_mean_i32, rank1_arithmetic_mean_i64, rank1_arithmetic_mean_r64
geometric_mean calls rank1_geometric_mean_i64, rank1_geometric_mean_r64, rank1_geometric_mean_r32, rank1_geometric_mean_i32
rank1_geometric_mean_i64 calls nth_root
rank1_geometric_mean_r64 calls nth_root
rank1_geometric_mean_r32 calls nth_root
nth_root calls nth_root_r64, nth_root_r32