union – Foreng
union Interface
5 statements
Source File
public interface union
Compute the union of two sets
Calls
Contents
Module Procedures
union_int union_r32 union_r64
Module Procedures
public function union_int(A, B) result(union_set)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: A
set A
integer, intent(in), dimension(:) :: B
set B
Return Value integer, dimension(:), allocatable
public function union_r32(A, B) result(union_set)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:) :: A
set A
real(kind=real32), intent(in), dimension(:) :: B
set B
Return Value real(kind=real32), dimension(:), allocatable
public function union_r64(A, B) result(union_set)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:) :: A
set A
real(kind=real64), intent(in), dimension(:) :: B
set B
Return Value real(kind=real64), dimension(:), allocatable
Call graph
union calls union_r32, union_int, union_r64
union_r32 calls belongs_to
union_int calls belongs_to
union_r64 calls belongs_to
belongs_to calls belongs_to_int, belongs_to_r32, belongs_to_r64
belongs_to_r32 calls array_epsilon
belongs_to_r64 calls array_epsilon
array_epsilon calls array_epsilon_r32, array_epsilon_r64
array_epsilon_r32 calls abs_max_val
array_epsilon_r64 calls abs_max_val
abs_max_val calls abs_max_val_r64, abs_max_val_r32